### ISSUE TITLE
`index` in `share` can bypass `types` restrictions

### ISSUE THREAD

**Issue by mqudsi** [nginx/unit#1079]
There is a possible security issue: the presence of `index` in a `share` section bypasses the mime types restrictions set in `types`. This leaks source code for some application types.

Example:

```json
	"routes": {
		"myapp": [
			{
				"match": {
					"uri": [
						"!.well-known/*",
						"~.*/\\..*"
					]
				},
				"action": {
					"return": 403
				}
			},
			{
				"match": {
					"uri": [ "*.php", "*.php/*" ]
				},
				"action": {
					"pass": "applications/myapp/direct"
				}
			},
			{
				"match": {
					"uri": "app/*"
				},
				"action": {
					"share": "`/var/www/myapp/${uri.substring(3)}`",
					"index": "index.php",
					"types": [ "!application/x-httpd-php" ],
					"fallback": {
						"pass": "applications/myapp/main"
					}
				}
			},
```

A request for `/app/dir1` will return the raw source code for `/app/dir1/index.php` if such a file exists, even though the `share` section has a mime type filter that is supposed to restrict it to non-php mime types.

**Comment by tippexs** [comment]
Thanks for the PR and the additonal context @alejandro-colomar we will have a look on the issues @mqudsi and let you know what are the next steps.

**Comment by tippexs** [comment]
@mqudsi Can you please send a Unit log with the `log_route` settings enabled and an example `curl` request to reproduce.

To enable the router logging use the following settings Object 
```
"settings": {"http": {"log_route": true}}
```

**Comment by hongzhidao** [comment]
Hi @mqudsi 
> A request for /app/dir1 will return the raw source code for /app/dir1/index.php if such a file exists, even though the share section has a mime type filter that is supposed to restrict it to non-php mime types.

Is this a real-world requirement for you? Or is it just a test to check how Unit work with `index` and `share`?

The current logic is`index` is to show the files in some directory, and `types` is to filter requests. The `types` don't filter specified `index`. And the default `index` is `index.html`.
Let us know if you have a more detailed read-world example to check if the current behavior is not good enough.

**Comment by alejandro-colomar** [comment]
@hongzhidao 

This is a regression introduced by you, presumably by accident, in one of those huge commits that sneak several refactors in.

The regression was introduced in c5220944d2ac ("Static: variables in the "share" option.").
```sh
$ git describe --contains c5220944d2ac
1.26.0~45
```

The logic you mention hasn't always been like that.  The original behavior is the one that the OP expected, and which I would also expect intuitively.

Below is proof of the original behavior:

```c
$ git show c5220944d2ac^:src/nxt_http_static.c | grepc nxt_http_static_send_ready .
./src/nxt_http_static.c:static void nxt_http_static_send_ready(nxt_task_t *task, void *obj, void *data);
./src/nxt_http_static.c:static void
nxt_http_static_send_ready(nxt_task_t *task, void *obj, void *data)
{
    ...

    r = obj;
    ctx = data;
    action = ctx->action;
    conf = action->u.conf;
    rtcf = r->conf->socket_conf->router_conf;

    f = NULL;
    mtype = NULL;

    shr = &ctx->share;
    index = &conf->index;

    if (shr->start[shr->length - 1] != '/') {
        path = shr;

    } else {
        length = shr->length + index->length;

        path = nxt_str_alloc(r->mem_pool, length + 1);
        if (nxt_slow_path(path == NULL)) {
            goto fail;
        }

        p = path->start;
        p = nxt_cpymem(p, shr->start, shr->length);
        p = nxt_cpymem(p, index->start, index->length);
        *p = '\0';
    }

    nxt_http_static_extract_extension(path, &exten);

    if (conf->types != NULL) {
        mtype = nxt_http_static_mtype_get(&rtcf->mtypes_hash, &exten);

        ret = nxt_http_route_test_rule(r, conf->types, mtype->start,
                                       mtype->length);
        if (nxt_slow_path(ret == NXT_ERROR)) {
            goto fail;
        }

        if (ret == 0) {
            nxt_http_static_next(task, r, ctx, NXT_HTTP_FORBIDDEN);
            return;
        }
    }

    ...
}
```

**Comment by hongzhidao** [comment]
> This is a regression introduced by you, presumably by accident, in one of those huge commits that sneak several unnecessary and dangerous refactors in.

> It is not a regression. It was introduced in the initial implementation of the feature with that behavior already. It was just that the sneaky refactor looked very suspicious, but it was a false positive.

> And another rabbit hole. I bet this rabbit is of the security subspecies.
Hi,

Below is a diff of nxt_http_static_send_ready() by the commit https://github.com/nginx/unit/commit/c5220944d2acdb912c129fc82ac8a83d24e9845d.

> It's quite unreadable (thanks for embedding a refactor there), so let's see the code before and after.

> The code for non-index cases, which for other reasons assumes 'shr' is
null-terminated, in this call assumes it's not null terminated.  Yes,
it's quite buggy in that regard.  That was a bug introduced in
https://github.com/nginx/unit/commit/c5220944d2acdb912c129fc82ac8a83d24e9845d ("Static: variables in the "share" option.").

I didn't find issues on the commit, and it has unit tests that passed.

Did you notice that you might be introducing worse performance and code readability?
```
path = nxt_str_alloc(r->mem_pool, length);
    if (nxt_slow_path(path == NULL)) {
        goto fail;
    }

... 

exten->length = end - p - 1;
```

Take the most common configuration as an example:
```
"share": ".../$uri"
```
And most of the requests have an extern for example, `/index.php`. In your new way:
1. Unit has to allocate memory twice. The current way only allocates once.
2. Developers who are interested in source code would be confused about number 1 in the tricky `end - p - 1`. They users read the source directly without reading the commit message.

**Comment by VBart** [comment]
This is an intentional behavior:
1. It doesn't make sense to restrict a file that user EXPLICITLY wrote in the static file serving configuration (note that "index" is about static file sharing, nothing else)
2. It allows to configure Unit to serve only directory indexes and protect any other files inside
3. Serving PHP sources is an issue only if a user had no intention to do so. But in this particular case user clearly stated his intention by specifying PHP file in the directive related to static file serving.

Actually, serving sources of PHP files can be useful not only for sharing the code, but also to store files on one instance and run them on another. Particular configuration allows to serve only directory index and protects any other PHP files in the directory. This can be a possible use case.

By fixing "this bug" you will change behavior and can break some existing configurations. Moreover, [this behavior is explicitly documented](http://unit.nginx.org/configuration/#mime-filtering), quote:
> If a share path specifies only the directory name, Unit doesn’t apply MIME filtering.

Has anyone read the documentation? =)

**Comment by alejandro-colomar** [comment]
> This is an intentional behavior:
> 
>     1. It doesn't make sense to restrict a file that user EXPLICITLY wrote in the static file serving configuration (note that "index" is about static file sharing, nothing else)

Yeah, with hardcoded index files it seems a bit silly.  I was thinking of variables in the `"index"` configuration, but in the end we didn't add that.  If the index would be generated via some NJS or some variable, it would be possible that the index file wasn't the intended one.  Also, if action chaining is ever implemented, it could also result in similar problems that an index file wasn't intended in some specific route.

> 
>     2. It allows to configure Unit to serve only directory indexes and protect any other files inside

Hmmm, this is interesting.  You could do the same thing with a `"match"` `"uri"` restriction, and check that the URI end in `/`.  But you have a point.

> 
>     3. Serving PHP sources is an issue only if a user had no intention to do so. But in this particular case user clearly stated his intention by specifying PHP file in the directive related to static file serving.
> 
> 
> Actually, serving sources of PHP files can be useful not only for sharing the code, but also to store files on one instance and run them on another. Particular configuration allows to serve only directory index and protects any other PHP files in the directory. This can be a possible use case.

Yep, this could be reasonable.  While you could also get this with some `"match"` `"uri"`, it would probably get tricky to write the rule.  Having a directory index could make it simpler.  I still have concerns about what will happen when Unit becomes a bit more complex, as I said above.

> By fixing "this bug" you will change behavior and can break some existing configurations.

Yeah, that would need to be considered.

> Moreover, [this behavior is explicitly documented](http://unit.nginx.org/configuration/#mime-filtering), quote:
> 
> > If a share path specifies only the directory name, Unit doesn’t apply MIME filtering.
> 
> Has anyone read the documentation? =)

=)

Still, there is a bug is some other code that Zhidao changed during some refactor, where a string should have a terminating null byte, but didn't.  I found that bug while editing this code.  That is fixed in the first patches of the PR.

**Comment by VBart** [comment]
> You could do the same thing with a `"match"` `"uri"` restriction, and check that the URI end in `/`.

If a request doesn't end with `/`, but points to a directory, it results in redirect to `uri/`. If you `match` only `uri/` then you will need another rule to maintain this redirect behavior. So, in order to completely replicate current behavior it requires more rules than it may seem on the first glance. More configuration usually means more error prone.

**Comment by hongzhidao** [comment]
> I found it by reading the source code, and the diffs, as documented in the commit messages.

You said you regarded it as a bug by reading the code but not testing it. But from the comments you posted, it looks like serious bugs happened.

> Is that performance difference meaningful? Probably not.

It was allocated twice but the current was allocated once...

> That's easy. When you have doubts about some code, check why it was changed, when, and how:

There is no `end - p - 1` in the past, then you introduce something like it.

I can't see the benefits of the change.

**Comment by tippexs** [comment]
@mqudsi coming back to you. After doing some more tests and validating the configuration options came to the conclusion this is not a bug if configured like mentioned above. The Documentation is clear about IF `share` for directory indexing the MIME-Filter will not take affect BUT will take affect for all files served via `share`.

Thanks for reporting. I will close this and we will work on your other, open issues.
