### ISSUE TITLE
Add support for writting application logs into stderr when Unit running inside of Docker

### ISSUE THREAD

**Issue by sidz** [nginx/unit#1124]
Hi guys.

I'm trying to run Nginx Unit inside of a Docker container with just one application inside of it. I'd like to write application logs to `stderr` and/or `stdout` streams so it will be possible to capture error logs and save it somewhere for example in the AWS Cloudwatch.

As far as I know it is not possible to write logs into `stderr` or `stdout` streams in `--no-daemon` mode. But it is not possible to run Nginx Unit inside of Docker container without this option.

Nginx Unit Docker template: https://github.com/nginx/unit/blob/master/pkg/docker/template.Dockerfile#L89.

Issue is extracted from https://github.com/nginx/unit/issues/915

cc @tippexs

**Comment by tippexs** [comment]
Hi @sidz sorry for the late response! 

There is a workaround I use in my Containers that is NOT what I consider a final solution but it works.

Instead of


```Dockerfile
CMD ["unitd .... "]
```

I use 

```Dockerfile
RUN unitd --control...
CMD ["tail -f /dev/null"]
```

This will let you configure per application logging to different files that can be combined or scraped by other tools. Let me know if this works for you!

**Comment by tippexs** [comment]
Hi @sidz sorry for the late response! 

There is a workaround I use in my Containers that is NOT what I consider a final solution but it works.

Instead of


```Dockerfile
CMD ["unitd, "OPTIONS"]
```

I use 

```Dockerfile
FROM unit:php

CMD ["/bin/bash", "-c", "unitd --log /dev/stdout; tail -f /dev/null"]
```

This will let you configure per application logging to different files that can be combined or scraped by other tools. Let me know if this works for you!

**Comment by sidz** [comment]
Thank you @tippexs !
I'll give it a try today and let you know.

As far as I understood you are writing application logs into files inside of container and it could be an issue as all our AWS instrastructure configured to scrap logs from the containers stderr/stdout and forward them to cloudwatch.

**Comment by tippexs** [comment]
If you would like to write all logs to `stdout` `stderr` then there is no need to change anything. Per default Unit in Docker will forward application logs to `stdout`. So there would be no need to define different logfiles if all of them are pointing to `/dev/stdout`.

**Comment by sidz** [comment]
That's an amazing news @tippexs. 

I did a new test with your image and it seems like it works like I expect!

> The only issue will be that you are unable to see what application created the log entry. 

That is not a problem for us as we will have just one application inside of container.

**Comment by sidz** [comment]
I'm going to close this ticket as I finally realized why Nginx Unit didn't write logs into stderr.

**Comment by martimors** [comment]
Care to share this wisdom? 🙏 

Have a container with a python app, and its `stderr` and `stdout` are not directed to the console.
