### ISSUE TITLE
building packages from latest github source

### ISSUE THREAD

**Issue by kalieye** [nginx/unit#113]
Hi,
i'm trying to build debian packages but i'm getting an error:

`dpkg-source: error: can't build with source format '3.0 (quilt)': no upstream tarball found at ../unit_1.0.orig.tar.{bz2,gz,lzma,xz}
dpkg-buildpackage: error: dpkg-source -b unit-1.1 gave error exit status 255
debuild: fatal error at line 1124:
dpkg-buildpackage -rfakeroot -us -uc failed
Makefile:155: recipe for target 'unit' failed
make[1]: *** [unit] Error 29
make[1]: Leaving directory '/root/new/unit/pkg/deb'
Makefile:15: recipe for target 'deb' failed
make: *** [deb] Error 2`

the process works correctly if i change the NXT_VERSION in src/nxt_main.h from 1.1 to 1.0 and i get the completed debs where they should be

**Comment by defanator** [comment]
Hi @kalieye, currently you have either to manually re-define the version to one of the existing versions in the https://github.com/nginx/unit/blob/master/docs/changes.xml, or add your own custom version to the same file in order to build a Debian package from non-tagged revision. First option could be used like this:

```
# cd unit/pkg/deb
# VERSION=1.0 make unit
```

The reason of having an ability to build packages from arbitrary revision was not considered as something demandable.

We could think of adding such an ability based on SCM features (e.g. generate custom version from latest tag + number of commits, or using changeset ID), but this may be a little bit complicated due to the fact that this Git repository is just a mirror of the official Mercurial repository (http://hg.nginx.org/unit), so both SCM systems should be covered ideally.

**Comment by kalieye** [comment]
ok, thanks a lot for the clarification!
