### ISSUE TITLE
Error configuring Flask/Python with official nginx/unit Docker image

### ISSUE THREAD

**Issue by Dominick-Peluso-Bose** [nginx/unit#137]
I've got a docker container built on `nginx/unit:1.2-python3.5`. I've copied my application and configuration files to it and am using the following configuration:
```json
{
    "listeners": {
        "*:80": {
            "application": "adapter"
        }
    },
    "applications": {
        "adapter": {
            "type": "python",
            "module": "app",
            "processes": 3,
            "path": "/app/src"
        }
    }
}
```

When I exec into the container, I can confirm that app.py is there:
```
root@35b58a21aa35:/# ls /app/src/app.py
/app/src/app.py
root@35b58a21aa35:/#
```

Applying the configuration returns:
```json
{
        "error": "Failed to apply new configuration."
}
```
This is a Flask app and when running on Gunicorn the module was resolved to `src.app:app`. I also tried doing the following which returned the same result:

```json
{
    "listeners": {
        "*:80": {
            "application": "adapter"
        }
    },
    "applications": {
        "adapter": {
            "type": "python",
            "module": "app",
            "processes": 3,
            "path": "/app/src/app"
        }
    }
}
```

What is the best way to go about debugging "Failed to apply new configuration."? Thanks!

**Comment by VBart** [comment]
Currently, more specific errors are not returned to the user, but logged into `unit.log`. It should be accessible from `docker logs`. This will be improved in the future.

In order to run Python application Unit does these steps:
 1. It adds a path from the `path` option to [`sys.path`](https://docs.python.org/3.5/library/sys.html#sys.path);
 2. Imports application WSGI callable using `from MODULE import application`, where `MODULE` is the value of the `module` option;
 3. Calls `application()` on request.

In your case the `path` option should be `/app/src` (the directory where your `app.py` module is located).

Also, it seems that your WSGI callable inside `app.py` is named `app()`. Currently there's no way to specify callable name in Unit. It uses `application()` as it the default name according to PEP. So, you have to change the name of callable function or make an another reference to it.

See also this discussion in mailing list: http://mailman.nginx.org/pipermail/nginx/2018-April/056102.html

**Comment by Dominick-Peluso-Bose** [comment]
Thanks for the response. It seems though it is still not working for me even when `application = app` is added to app.py.

I am trying to cat `/var/log/unit.log` but it looks like there is nothing in that file. Any idea what I'm doing wrong?

**Comment by Dominick-Peluso-Bose** [comment]
So I made this file `/tmp/sanity.py` and put it on the container. I then installed Python 3.
```python
import sys
sys.path.append('/app/src')

from app import application

print(type(app))
```
Which results in an error because I'm using fstrings (since my app targeted Python 3.6). 
```
root@d5ac3e64f451:/app/n-unit# python3 sanity.py
Traceback (most recent call last):
  File "sanity.py", line 4, in <module>
    from app import application
  File "/app/src/app.py", line 816
```
So it does load as configured but it won't run on this version of Python. Would this also cause the "Failed to apply new configuration." error?

**Comment by VBart** [comment]
Inside docker the `unit.log` is routed to log collector:
```
# forward log to docker log collector
RUN ln -sf /dev/stdout /var/log/unit.log
```
So, it can be read only from `docker logs` command.

Yes, if it can't import application due to syntax error the configuration wouldn't apply. Because f-strings are only supported since 3.6, so it expected to fail on 3.5 and a traceback should appear in the log.

**Comment by KursLabIgor** [comment]
I've just rename app to application in my wsgy.py file. And i able to start application.

**Comment by tippexs** [comment]
Closed due to timeout
