### ISSUE TITLE
IRC channel?

### ISSUE THREAD

**Issue by mpmc** [nginx/unit#148]
Something I noticed..

Pretty much as title, is there an IRC channel? If not, why not?

:)

**Comment by igorsysoev** [comment]
We are not so old to hang out on IRC :)

**Comment by mpmc** [comment]
True, but it looks like someone already created one, just no one in it but me. :rofl:

**Comment by sysdef** [comment]
Even young developer are using the worlds largest Developer and Support Network freenode.net .

**Comment by sysdef** [comment]
Looks like you're missing hundred of professional user and supporter that way.

Channel #nginx has 688 user

 -!- Topic for #nginx: [Stable: 1.14.0] [Mainline: 1.15.2] <+> Unofficial community support for nginx--primarily an HTTP and reverse proxy server. <+> Don't ask to ask; just ask a specific, clear, and concise question/problem/goal. Include configs on our !pastebin at https://paste.ngx.cc (see: !whypbin). Be patient and wait for a response.

**Comment by MTecknology** [comment]
@igorsysoev Howdy! I don't know if you have memory/logs of 09 June 2009--I barely do. Back then, we'd discussed making #nginx on freenode an official support channel. In order to make that happen, freenode required you[Igor] to create a TXT record or text file (can't remember which) on nginx.org (back before nginx.com existed).

When you did this, you also confirmed me as a Group Contact, which gave me authorization to take ownership of #nginx (previously unmanaged, and heavily spammed) and also gave me authority over anything in the #nginx* namespace. It also allowed us to begin allocating @nginx/* hostmasks. (channel ops are given @nginx/adept/<username>)

@sysdef Until reading this issue, I was unaware that #nginx-unit existed. As the channel was empty, I took ownership of it and set it up to forward to #nginx. I'd be happy to change that in the future, but for now, I want to avoid users winding up in dead channels.


#nginx is a moderately active channel for support, but few developers hang out in there so dev questions are almost always directed to the mailing list. There used to be two active nginx employees, but now we're down to just thresh (Konstantin P.), who is a delight to have around.

This may also be worth noting: https://www.nginx.com/resources/wiki/community/irc/

**Comment by ac000** [comment]
In case anyone else comes here looking, it seems the IRC channel has moved to #nginx on irc.libera.chat (I guess since the recent freenode happenings...).

**Comment by tippexs** [comment]
We do have a NGINX Community slack now. https://community.nginx.org/joinslack
