### ISSUE TITLE
New Node.js module build error

### ISSUE THREAD

**Issue by Zmeu213** [nginx/unit#180]
Hi there. Im trying to install `unit-http` module with `npm i unit-http` and I got this error
```> unit-http@1.5.1 install /home/kirill/unit-hello/node_modules/unit-http
> node-gyp configure build

make: Entering directory '/home/kirill/unit-hello/node_modules/unit-http/build'
  CXX(target) Release/obj.target/unit-http/unit.o
In file included from ../unit.cpp:6:0:
../unit.h:17:22: fatal error: nxt_unit.h: No such file or directory
compilation terminated.
unit-http.target.mk:100: recipe for target 'Release/obj.target/unit-http/unit.o' failed
make: *** [Release/obj.target/unit-http/unit.o] Error 1
make: Leaving directory '/home/kirill/unit-hello/node_modules/unit-http/build'
```

tested on node v10.13.0 and v8.12.0 (npm v6.4.1)

**Comment by VBart** [comment]
@Zmeu213 Have you installed the unit-dev/unit-devel package? It contains the libunit and header files required to build the module. 
http://unit.nginx.org/installation/#installing-required-software

**Comment by Zmeu213** [comment]
As referenced in http://unit.nginx.org/installation/#installing-required-software `unit-dev` is required so `apt-get install unit-dev` solved my problem

**Comment by Zmeu213** [comment]
Yup, documentation is just a little bit confusing.

**Comment by VBart** [comment]
@Zmeu213 I agree. Currently we are working on improvements to the documentation.

**Comment by wnyao** [comment]
Hi, sorry to interrupt as i needed some help with similar issue.

I am facing the issue with `nxt_unit.h` not found. Tried to install unit-dev with `apt-get install unit-dev` and got responded that package not found. Are there any other ways that can solve this?

My goal is to run an simple Express application within nginx/unit docker image. Instead of mounting application files to a directory in the container, i created a new express app within the container. As specified within the doc, it is needed to configure Express application to utilize unit-http instead of http.

This error can be reproduce within the docker container running `nginx/unit:latest`

### Response from installing unit-http
```
root@a07c8077837b:/home/test-express# npm install -g --unsafe-perm unit-http

> unit-http@1.10.0 install /usr/lib/node_modules/unit-http
> node-gyp configure build

make: Entering directory '/usr/lib/node_modules/unit-http/build'
  CXX(target) Release/obj.target/unit-http/unit.o
In file included from ../unit.h:9:0,
                 from ../unit.cpp:6:
../nxt_napi.h:17:22: fatal error: nxt_unit.h: No such file or directory
 #include <nxt_unit.h>
                      ^
compilation terminated.
unit-http.target.mk:98: recipe for target 'Release/obj.target/unit-http/unit.o' failed
make: *** [Release/obj.target/unit-http/unit.o] Error 1
```

### Response from installing unit-dev
```
root@a07c8077837b:/home/test-express# apt-get install unit-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package unit-dev
```

**Comment by mar0x** [comment]
@wnyao You need to add Unit repository to your apt configuration. Please read this page http://unit.nginx.org/installation/#ubuntu .

**Comment by wnyao** [comment]
@mar0x Thanks for the response. Was thinking that nginx/unit docker image come with the installation by default and later found out that the docker image still require to go through the installation process.
