### ISSUE TITLE
unit-go RPM build failure on Fedora 29

### ISSUE THREAD

**Issue by remicollet** [nginx/unit#214]
```
+ make go-install
make[2]: Entering directory '/work/GIT/unit/pkg/rpm/rpmbuild/BUILD/unit-go-1.8'
install -d /work/GIT/unit/pkg/rpm/rpmbuild/BUILDROOT/unit-go-1.8-1.fc29.remi.ngx.x86_64/usr/share/gocode/src/nginx/unit
install -p -m644 ./src/*.h ./build/*.h ./src/go/unit/*     ./src/nxt_unit.c ./src/nxt_lvlhsh.c ./src/nxt_murmur_hash.c     /work/GIT/unit/pkg/rpm/rpmbuild/BUILDROOT/unit-go-1.8-1.fc29.remi.ngx.x86_64/usr/share/gocode/src/nginx/unit/
GOPATH=/work/GIT/unit/pkg/rpm/rpmbuild/BUILDROOT/unit-go-1.8-1.fc29.remi.ngx.x86_64/usr/share/gocode go build nginx/unit
# nginx/unit
In file included from nxt_cgo_lib.c:10:
../../BUILDROOT/unit-go-1.8-1.fc29.remi.ngx.x86_64/usr/share/gocode/src/nginx/unit/nxt_unit.h:14:10: fatal error: nxt_unit_version.h: No such file or directory
 #include "nxt_unit_version.h"
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.

```

**Comment by defanator** [comment]
@remicollet this one is related - https://github.com/nginx/unit/commit/604a2f21f1a73e9f183b2b005e517e0647d59827 (we put it into the `packaging` branch as we use that branch in our release process, but the initial bug should be fixed in master as well, we have a pending task for this)

**Comment by VBart** [comment]
This issue was introduced in Unit 1.7 by https://github.com/nginx/unit/commit/c55f329ecf8d32bad0d5bc2aae1da1522b3a92f8. Now the Go module depends on `nxt_unit_version.h`, which is created during `make`.

So, as a workaround the following commands should work:
```
./configure go
make
make go-install
```
That will be fixed in Unit 1.8 (end of February).

**Comment by remicollet** [comment]
Would it be possible to cherry-pick the relevant commit, to allow more test in master ?

**Comment by VBart** [comment]
@remicollet That's something we'd like to avoid, since this commit is just a temporary workaround for packaging and will be reverted anyway. The proper fix is completely different and should return the ability to install Go module without building Unit.

I've asked @lexborisov to prioritize work on this issue.
