### ISSUE TITLE
Unable to install npm package

### ISSUE THREAD

**Issue by imvetri** [nginx/unit#239]
![unit-http_npm_install](https://user-images.githubusercontent.com/6542274/55331081-2bf58a00-54b0-11e9-925e-df6d2ffffb6b.png)

**Comment by mar0x** [comment]
Looks like you are faced with [this issue](https://github.com/nodejs/node-gyp/pull/1455). Consider upgrade your node-gyp installation.

**Comment by imvetri** [comment]
I installed npm-gyp latest version and it fails still. Is it an issue with npm-gyp ?

**Comment by imvetri** [comment]
@mar0x FYI - This blocks me from trying out nginx/unit for nodeJS.

**Comment by mar0x** [comment]
@imvetri 

Since we have no packages for OS X, you need to install Unit + NodeJS from sources (see http://unit.nginx.org/installation/#source-code ). It is still requires working node-gyp and it is possible to fix the regular expression in sources: apply [this patch](https://github.com/nodejs/node-gyp/pull/1455/commits/46e630e8ae9d4214ca46446fa84d1681aa57f61b) manually.

Please let us know if you have other issues which blocks you from trying Unit.

**Comment by mar0x** [comment]
@imvetri 
Have you installed Unit + NodeJS ? Any new issues ?

**Comment by imvetri** [comment]
@mar0x Thanks for the patch, I'm yet to give it a try.

**Comment by tippexs** [comment]
closed due to timeout
