### ISSUE TITLE
TypeError: this._implicitHeader is not a function

### ISSUE THREAD

**Issue by R4z0R7** [nginx/unit#240]
Hello,

I'm trying to run an express application that's using compression:
https://github.com/expressjs/compression/blob/master/index.js

The compression module uses the _implicitHeader function, which exists in the original http module. However, I see that this function was removed here:
https://github.com/nginx/unit/commit/d9dad07934c17319b6aecd5b4958cdef3a196ad0

Because of that, the application starts in unit but throws an error:
/home/hackra661/nodeapp2/node_modules/compression/index.js:102
        this._implicitHeader()
             ^

TypeError: this._implicitHeader is not a function

If I manually add the missing lines, which describe the implicitHeader function, to node_modules/unit-http/http_server.js, the application works.

Why is this function removed from unit-http ? Is unit-http fully compatible with the original http module of node ? Are there any npm packages which are not compatible with unit ?

**Comment by VBart** [comment]
This function isn't documented in [Node.js API](https://nodejs.org/api/http.html) and `_` in the name indicates that this is internal function which should not be called outside. Unfortunately the compression module uses undocumented functionality, as the result causes compatibility issues even if the API follows the original http module as it's declared. See similar issues in other projects: https://github.com/apigee/trireme/issues/124

I believe it's the compression module must be fixed, but we should revert https://github.com/nginx/unit/commit/d9dad07934c17319b6aecd5b4958cdef3a196ad0 in order to be compatible with existing code. It was removed because nobody at that moment remembered the reason why it was added and where it was used.

Thank you for your report.

**Comment by VBart** [comment]
There's also a pull request to fix the issue in the compression module: https://github.com/expressjs/compression/pull/155
