### ISSUE TITLE
[question] How to check node server started with unit or not?

### ISSUE THREAD

**Issue by academici** [nginx/unit#247]
server.config.js
```js
const isNginxUnit = () => {
  return true; // ???
}

export default {
  // Use custom adapter for server
  adapter: isNginxUnit() ? FastifyUnitAdapter : FastifyAdapter,
}
```

**Comment by mar0x** [comment]
1. try to create unit-http server, catch exception for fallback:
  ```
  try {
      server = require('unit-http').createServer(...);
      ...
  } catch(e) {
      server = require('http').createServer(...);
  }
  ```
2. check the ```NXT_UNIT_INIT``` environment variable:
  ```
  if (process.env.NXT_UNIT_INIT) {
     ...
  }
  ```
3. introduce, configure in unit application config and check in app your own environment variable or command-line parameter

Last approach (`#3`) is most reliable and generic;
`#2` relies on current implementation and can be changed at any time;
`#1` is robust enough, but cannot be used in configuration js because of side-effects and error messages;

**Comment by academici** [comment]
Thanks!
