### ISSUE TITLE
invalid port in "socket"

### ISSUE THREAD

**Issue by Tricky-Ricky** [nginx/unit#270]
I ran the command:

`sudo unitd --control socket`

And it returned with error:

`[error] 32265#32265 invalid port in "socket"`

Installed by following the documentation for Ubuntu 18.04, and nodejs, as far as I am aware the only ports I have open for the server are port 80 and port 443 - Are either of these in use for unit after installation, and if so how do I find and configure the relevant file?

**Comment by VBart** [comment]
If you want to override compile-time socket address, then after the `--control` option you have to specify the actual address of the control API socket instead of word `socket`, e.g.: ```--control 127.0.0.1:8888``` for IPv4 or ```unix:/var/run/unit/control.sock``` for Unix domain socket path.

The only port in use by Unit after the installation is the control socket port and only if it was configured as IP address instead of Unix domain path. All other ports can be configured via control API in `listeners` object: https://unit.nginx.org/configuration/#listeners

**Comment by Tricky-Ricky** [comment]
Hi VBart

Thanks for clarifying that, Howeverif I try to open control.sock in NANO - It is a blank file, with NANO outputting that it is a special file?

**Comment by VBart** [comment]
It's a Unix domain socket, see: https://en.wikipedia.org/wiki/Unix_domain_socket

It works similar to other sockets, but instead of IP address and port number representation, it's mapped to the file system and represented as a special file. You can't open it in a file editor, because it's not a regular file, but you can connect to it using `curl` or any other client.

See the documentation for examples and basics: http://unit.nginx.org/configuration/#configuration-management
