### ISSUE TITLE
Need 404 header for not existing php script

### ISSUE THREAD

**Issue by solo-framework** [nginx/unit#287]
Hello everyone

There is a part of  nginx proxy:
```
location ~* \.php$ {
			proxy_pass http://scripts_backend;			
			proxy_set_header Host $host;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header X-Forwarded-Proto $scheme;
			proxy_intercept_errors on;
		}
	upstream scripts_backend {
		server nginx-unit:8301;
	}
```
Unit config is 
```
{
	"listeners": {
		
		"*:8301": {
			"application": "direct_scripts"
		}
	},
	"applications": {
		
		"direct_scripts": {
			"type": "php 5.6",
			"processes": 1,
			"root": "/www/root",
			"index": "index.php",
			"options": {
				"admin": {
					"error_reporting": "32767",
					"display_errors": "1"
				}
			}			
		}
	}
}
```

Nginx unit 1.9.0

When I do request for `localhost/not_exists.php` I get an error:

_Warning: Unknown: failed to open stream: No such file or directory in Unknown on line 0
Fatal error: Unknown: Failed opening required '/www/root/not_exists.php' (include_path='.:/usr/share/php') in Unknown on line 0_

The error has HTTP 200 if `"display_errors": "1"` and with HTTP 500 if `"display_errors": "0"`.
It seems to me it should return 404 like an error "No input file specified. " for php-fpm.

**Comment by VBart** [comment]
The idea here is that passing non-existing script for handling by PHP interpreter in Unit is server misconfiguration (i.e. 500 internal error). This also allows Unit to save some syscalls on checking file presence. When `display_errors` is turned on, the exception is intercepted by PHP interpreter itself, which returns 200 in this case.

You should add `try_files` directive to nginx configuration in order to avoid passing such request to Unit. In future versions we will add the `try_files` feature to Unit itself.

**Comment by solo-framework** [comment]
> The idea here is that passing non-existing script for handling by PHP interpreter in Unit is server misconfiguration (i.e. 500 internal error). This also allows Unit to save some syscalls on checking file presence. When `display_errors` is turned on, the exception is intercepted by PHP interpreter itself, which returns 200 in this case.
> 
> You should add `try_files` directive to nginx configuration in order to avoid passing such requests to Unit. In future versions we will add the `try_files` feature to Unit itself.

**Comment by solo-framework** [comment]
@VBart 

[In docs](https://unit.nginx.org/configuration/#php) we can read:

> The `index` and `script` options enable two modes of operation:

 >  1. If `script` is set, all requests to the application are handled by the script you provide.
 >   2. Otherwise, the requests are served according to their URI paths; if script name is omitted, index is used.

I use `index` mode, so user is able call any url (for example /wrong-name.php). But it's not a server misconfiguration! The file `wrong-name.php` really doesn't exist and it is nothing but "file not found" 404 error.

> You should add try_files directive

Adding `try_files  $uri =404;` into `location ~* \.php$` section is useless because this instance of nginx  contain only static files. And it will return 404 always for all requests even for existing php scripts.  Or what did you mean?

**Comment by VBart** [comment]
@solo-framework Unit currently doesn't check if a php script exists or not. It just passes all the URIs to the PHP interpreter that generates exception in this case with 500 response. PHP-FPM does additional handling here in order to return 404 or 403 responses. We have plans for implementing something like `try_files` on the Unit side in the future in order to handle this situation too.

Anyway if you use nginx in front, then the most effective way of handling such requests is to do it on nginx side without passing them further and occupying PHP worker processes (PHP-FPM or Unit doesn't matter, it will waste of resources). For this you need all the php files on your nginx instance in order to `try_files` work correctly there.

**Comment by solo-framework** [comment]
@VBart ok, thanx for comments
