### ISSUE TITLE
Support for chroot in app config

### ISSUE THREAD

**Issue by artemkonev** [nginx/unit#391]
A feature to enable restricting the file system of the app process by setting the root filesystem to an arbitrary directory.
    
Corresponding app config will be similar to this:

    {
        "type": "python",
        "path": "/app",
        "module": "wsgi",
        "isolation": {
            "rootfs": "/images/debian"
        }
    }

**Comment by smtalk** [comment]
Would be it possible to add ro-bind/bin directives there? So that we could simply place the process in a namespace where user still has OS-executables in place, and other things completely hidden :)

I'd suggest checking https://github.com/containers/bubblewrap implementation.

We use something like this for complete user isolation in shell/cron:
```set -euo pipefail
(exec bwrap --ro-bind /usr /usr \
      --ro-bind /lib /lib \
      --ro-bind /lib64 /lib64 \
      --ro-bind /bin /bin \
      --ro-bind /sbin /sbin \
      --dir /var \
      --dir /tmp \
      --symlink ../tmp var/tmp \
      --proc /proc \
      --dev /dev \
      --bind ${HOME} ${HOME} \
      --ro-bind /etc/localtime /etc/localtime \
      --ro-bind /etc/ld.so.cache /etc/ld.so.cache \
      --ro-bind /etc/resolv.conf /etc/resolv.conf \
      --bind /var/lib/mysql/mysql.sock /var/lib/mysql/mysql.sock \
      --chdir ${HOME} \
      --unshare-all \
      --share-net \
      --die-with-parent \
      --dir /run/user/$(id -u) \
      --setenv XDG_RUNTIME_DIR "/run/user/`id -u`" \
      --setenv PS1 "${USER}$ " \
      --file 11 /etc/passwd \
      --file 12 /etc/group \
      /bin/bash) \
    11< <(getent passwd $UID 65534) \
    12< <(getent group $(id -g) 65534)
```

I don't mind if "unit" had a way to start the apps directly in bubblewrap, if you wouldn't like to support it natively. At this time even if application is put to its own namespace in Nginx Unit - it can still see all the processes in processlist (`ps auxwf`), all the users in /etc/passwd, all the files in /etc and so on (yes, permissions limit them on what they can/cannot read, but they can still list the files etc.).

"rootfs" would solve the files problem, but it'd require having prefered bins in that /images/debian/bin/.. folder (or any other one, which is set as rootfs). In addition to this - it doesn't change what processes would be seen processlist, because even with all the namespaces enabled, whole system `/proc` is seen. Same issue with `/dev`. I'd like to note that:
```"pid": true,```

Is set :)

Bubblewrap is a small implementation in pure C, if you'd like to check.

**Comment by i4ki** [comment]
Hi @smtalk,

The `rootfs` feature will bind mount the language libraries for the module language being used and we plan to add support for additional mounts specified by user config in the future.
The issue you mentioned about other processes being visible in /proc is because of the missing chroot feature. This will be fixed with the rootfs release as the procfs is remounted in the new namespace (also /dev will not be visible anymore).

**Comment by smtalk** [comment]
@i4ki - really glad to hear this. I hope it'll have ability to mount tmpfs on top to "hide" some endpoints like /usr/lib/modules or /usr/lib/systemd, and that it'd hide all the other users in /etc/passwd and /etc/group. Thank you for your hard work, it's really appreciated!
