### ISSUE TITLE
Initial Configuration directive

### ISSUE THREAD

**Issue by codecowboydotio** [nginx/unit#577]
I would like to humbly ask for a new configuration directive on unit startup.

The ask:
----------
When starting the unitd binary, it would be useful to have a configuration argument that allows me to set a URL to source the initial configuration from.

Something like the following:
```
unitd --no-daemon --modules /usr/lib/unit/modules --control 0.0.0.0:8888 --pid /fooble/unit.pid --log /fooble/unit.log  --config-url http://me.com/unit-config.json
```
**--config-url** is a new argument that sources the initial unit configuration from a URL.

The use case:
---------------
The use case for this is when running in a container.
If I am able to source the initial unit configuration from a URL, then I am much more dynamic in nature and can set the URL as an environment variable that gets passed into the container on instantiation.

This would be used for initial bootstrap only.

This would also be extremely helpful in the event of a pod / container restart.

In an event driven world, this should be automagic.
In an eventually consistent world like k8s, then there is a problem with pod restart where there is no initial boostrap for the pod other than a static bootstrap.

Alternatives:
--------------
I can do this currently by modifying my entrypoint, and using shell scripts. 
This seems a little "hacky" in many ways, and is not dynamic in nature.
I want a dynamic way of passing a variable to the container on startup rather than "baking in" a specific configuration or URL / entrypoint modification.

The world according to me:
-------------------------------
Get ready.....

- I would like to have a single option for downloading a configuration into the unit via a URL that does not require modifications to my entrypoint with strange shell scripts. 
- I would like to have this option availble as part of the binary and a "standard" option so that I can test on bare metal **and** within a container. 
- I would like to make sure that the configuration I pull down at unit startup is an "instantiation" configuration - recognizing that it may change over time.

The benefits:
----------------
I believe that this would benefit the unit community in the following ways:

- Allow for an initial bootstrap configuration to be loaded for unit regardless of the final configuration.
- Allow for a standardised way of providing an initial configuration.
- Allow for a decoupled initial configuration experience at intial startup.
- Allow for a standard "default" configuration at startup whereby further configuration is performed via a CI or CD pipeline.
- Allow for a standard way of loading user specified applications and or configuration directives at initial instantiation time.

Please let me know if further clarity or discussion is needed. :)

**Comment by codecowboydotio** [comment]
As an aside - I have temporarily modified my entrypoint for my container with the following:

```

download_config()
{
set -x
  CONFIG_URL=$1
  if [ -z CONFIG_URL ]
  then
    echo "No URL was passed to the download config function - no config will be downloaded"
  else
    curl -s $CONFIG_URL | tee -a | curl -X PUT 127.0.0.1:8888/config -d @-
  fi
}
download_config ${UNIT_CONFIG_URL}

```

While this works, and I can pass these as environment variables into my pod at startup like this:

```
        env:
          - name: UNIT_CONFIG_URL
            value: "https://x.y.z/initial-unit-config.json"
```

It is a little ugly and would be nice if unit had an argument that I could pass. :)

**Comment by VBart** [comment]
It just looks like a simple option, because you're looking at very narrowed use case that barely will work for many of our users.

Just a few points those immediately comes to mind (and I can't even imagine how many other pitfalls will be revealed during implementation and usage):
1. It looks as just one option unless you have authorization... then what type of authorization? Client cert, password, basic auth, whatever? You will end up with 5+ more options to configure and provide all that in the command line just for one initial start.
2. Initial configuration doesn't include just one JSON object. Even in current versions of Unit it may also use certificates for HTTPS configuration. Those certificates need to be uploaded first, before the JSON configuration will be uploaded. In future there will be even more other different objects like JS modules, client keys and certificates, container files... etc., and all these objects will be referred in the configuration and will need to be provided first before applying the initial configuration. So, you will end up not with just one config URL, but with hundreds of URLs of different objects to download.
3. It raises many other questions, e.g.: how to react on redirects? what to do if connection or request fails? how long to wait if the download freezes?

Just check `man curl` how many possible option a typical HTTP client has to configure. And anybody can easily do it in their bootstrap scripts, but moving all that functionality inside the unit daemon just violates the KISS principle which we prefer to stick.

**Comment by VBart** [comment]
Note that our official docker images already provide a pretty handy way of initial configuration, where you can add bootstrap scripts in order to download all the needed files: https://unit.nginx.org/installation/#initial-configuration

**Comment by lcrilly** [comment]
+1 to VBart's comments. Putting a network dependency on the initial configuration looks like a recipe for complexity and unpredictable behaviour. Especially when an effective workaround is to use curl/wget to populate the `--state` directory _before_ the daemon is started.

Closing as not planned.
