### ISSUE TITLE
HTTP redirect to HTTPS

### ISSUE THREAD

**Issue by olszakjakub** [nginx/unit#578]
Hi, is there any easy way to redirect HTTP traffic to HTTPS? I didn't find any official way of doing that and only this workaround: https://github.com/nginx/unit/issues/353. Am I missing something or isn't it an obvious thing?

**Comment by VBart** [comment]
See here: https://unit.nginx.org/configuration/#instant-responses-redirects - isn't it what you're looking for?

**Comment by olszakjakub** [comment]
That was it. Dunno how i missed it. Thanks.

**Comment by jansaputra** [comment]
That doesn't really solve the problem completely, right? We can't do resource based redirects like in the workaround in https://github.com/nginx/unit/issues/353 . So for example, one often wants to redirect something like http://foo.com/abc/def to https://foo.com/abc/def . Is there any way to do that without writing a helper application?

**Comment by alejandro-colomar** [comment]
`Add variables in "location"` didn't fully solve this issue, since we also needed `$request_uri`.  `$uri` is problematic with location, because its contents are decoded, while location expects encoded URIs.  I'm reopening, and linking against the patch adding `$request_uri`.

Footnote:  Do NOT use `$uri` in `"location"` unless you really understand what you're doing.

**Comment by alejandro-colomar** [comment]
`Var: Added $request_uri (as in NGINX)` was merged.
