### ISSUE TITLE
Queue overflow when downloading a file

### ISSUE THREAD

**Issue by alexmaslenn** [nginx/unit#587]
We are running app based on the Django framework using Unit. Trying to serve not a relatively large file (~1 MB) as Django `FileResponse` we encounter an `queue overflow` error. Download stops at random point, or does not even start with an empty response. Smaller files (few KB) work fine. 
unit.log
```
{"asctime": "2021-09-30 08:47:45,018", "levelname": "INFO", "message": "\u001b[36mGET /api/report/4/pdf/\u001b[0m", "request": "<WSGIRequest: GET '/api/report/4/pdf/'>", "response": null}
{"asctime": "2021-09-30 08:47:45,019", "levelname": "INFO", "message": "\u001b[36mGET /api/report/4/pdf/ - 200\u001b[0m", "request": "<WSGIRequest: GET '/api/report/4/pdf/'>", "response": "<django.http.response.FileResponse object at 0x7feb081a67b8>"}
2021/09/30 08:47:45 [alert] 186363#186363 [unit] port_send: port 186362,1 queue overflow
```
Full debug log in attachment [unit_log.zip](https://github.com/nginx/unit/files/7258252/unit_log.zip)

Unit configuration
```
unit version: 1.25.0
configured as ./configure --prefix=/usr --state=/var/lib/unit --control=unix:/var/run/unit/control.sock --pid=/var/run/unit/unit.pid --log=/var/log/unit/unit.log --tmp=/var/tmp --user=unit --group=unit --tests --openssl --modules=/usr/lib64/unit/modules --libdir=/usr/lib64 --cc-opt='-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC' --ld-opt='-Wl,-z,relro -Wl,-z,now -pie'
```

Unit HTTP settings
```json
        "settings": {
                "http": {
                        "header_read_timeout": 100,
                        "body_read_timeout": 100,
                        "send_timeout": 100,
                        "idle_timeout": 1200,
                        "max_body_size": 26214400
                }
```

System running is `CentOS Linux release 8.4.2105` on an x86_64

**Comment by mar0x** [comment]
Ok. Maybe you want to grep all the sources and `block_size` changed in other place?

Another possible reason based on the fact `FileResponse` uses `block_size` only if streaming content object [has attribute `read`](https://github.com/django/django/blob/98c8bf1ceeab5c68751c83555f82cff1a9120a67/django/http/response.py#L443) (i.e. file), otherwise it iterates over this object [passings it's elements through `make_bytes()`](https://github.com/django/django/blob/98c8bf1ceeab5c68751c83555f82cff1a9120a67/django/http/response.py#L412). So, please check how `FileResponse` initialised, what object passed to constructor?

If you share the sample application to reproduce the issue, I can try to find the reason myself.

**Comment by alexmaslenn** [comment]
@mar0x that was a great insight, thank you. This was exactly the problem, wrapping in `BytesIO` solved the issue.
