### ISSUE TITLE
Can I use NGINX UNIT without NGINX?

### ISSUE THREAD

**Issue by TRcodes** [nginx/unit#617]
I am still a beginner and it is hard to understand how to use without NGINX. Applications open on different ports. i.e. these ports need to be opened in the firewall. I want all applications to use port 80 but different links will be opened by different applications. It is also not clear if there is a possibility to cache static files.

The main question I want to understand is whether it is possible to fully use NGINX UNIT without NGINX?
If yes, then I will continue to read the manual to understand all the charms of routing.

**Comment by mar0x** [comment]
Hello.
Yes, it is possible to use Unit without NGINX. Though static files cache is not implemented yet.

**Comment by TRcodes** [comment]
@mar0x 
Does your task list have caching? And when can this functionality be expected?

**Comment by VBart** [comment]
@TRcodes  Caching is a big feature that would be nice to have, but it's an extended functionality that not everyone needs. Since there are still plenty of essential features not implemented yet, the caching isn't among the todo list for the nearest future. I can't predict any ETA for it at the moment.
