### ISSUE TITLE
How I can start express application with nodemon on nginx-unit?

### ISSUE THREAD

**Issue by Pavlusha311245** [nginx/unit#627]
I think it is possible to change the configuration, but when the file changes, nginx stops responding and writes a configuration error.
<img width="466" alt="Screenshot 2021-12-27 at 4 37 38 PM" src="https://user-images.githubusercontent.com/49598333/147476955-939431b3-420b-4792-a85c-2b9caf9b12f9.png">
Error if you delete a key with arguments or executable:
<img width="367" alt="Screenshot 2021-12-27 at 4 37 53 PM" src="https://user-images.githubusercontent.com/49598333/147476967-3786961c-0a36-48bc-8759-1758184697f5.png">

**Comment by mar0x** [comment]
Hello.
It is not clear what exactly goes wrong. Please describe in detail what you are doing, what is expected and the errors you get.

Configuration without `executable` key is invalid because Unit need at executable file to start.
Without `arguments`, the executable `/usr/bin/env` just prints all environment variables and exits. This is not what Unit expects from web application.

More detailed errors you may find in `unit.log`.

If you want to restart the application, you may ask Unit to do it (see [Process Management](https://unit.nginx.org/configuration/#process-management)).

**Comment by mar0x** [comment]
The short answer to the question _"How I can start express application with nodemon on nginx-unit?"_  is _"In no way"_.

Unit need to start and manage application processes just like `nodemon` wants to, so currently you are limited to run "plain" `node` application processes.
