### ISSUE TITLE
FR available variables for location

### ISSUE THREAD

**Issue by jamesRUS52** [nginx/unit#667]
Hi, please add variables to location section like this

```
"action": {
        "return": 301,
        "location": "https://${host}${uri}"
    }
```

**Comment by tippexs** [comment]
Hi @jamesRUS52 thanks for reaching out. We are currently working on an implementation. See [PR](https://github.com/nginx/unit/pull/660). Will tag your Issue and close it once the feature is generally available.

**Comment by jamesRUS52** [comment]
thank you

**Comment by alejandro-colomar** [comment]
`Add variables in "location"` didn't fully solve this issue, since we also needed `$request_uri`.  `$uri` is problematic with location, because its contents are decoded, while location expects encoded URIs.  I'm reopening, and linking against the patch adding `$request_uri`.

Footnote:  Do NOT use `$uri` in `"location"` unless you really understand what you're doing.

Use:

```json
"action": {
        "return": 301,
        "location": "https://${host}${request_uri}"
}
```

**Comment by alejandro-colomar** [comment]
`Var: Added $request_uri (as in NGINX)` was merged.
