### ISSUE TITLE
Unusual http response status

### ISSUE THREAD

**Issue by hongzhidao** [nginx/unit#72]
Hi!

In unit, the response status is regarded as a normal header, 
not an individual line specified in RFC
``` The first line of a Response message is the Status-Line,  ... ```
Is this to simplify handling parse and application (php, python, go, etc)?

Thanks!

**Comment by VBart** [comment]
There are a number of reasons:
1. That was a temporary solution, since we already had an HTTP/1.x header parsing function. There's no need in HTTP between the router and application processes, and in the future that will be replaced with an effective binary protocol.
2. This is actually similar to CGI specification.
3. There's no status line in HTTP/2 anyway.

**Comment by hongzhidao** [comment]
Thanks for your reply!

Maybe the status-line parsing function will be added if unit support http proxy.

BTW, how the source file in NXT_LIB_SRC0 will be dealt, 
such as nxt_buf_filter.c, nxt_XXX_source.c?
They seem to be related to upstream like in nginx.
How will these be dealt in the future? Removed or refactor?

Moreover, some questions about the project code.
It has many big changes from initial version, it's quite different from nginx.
This situation seems to continue, especial the part of router.

Anyway, it's a great job. Thanks again.

**Comment by VBart** [comment]
This is an evolutionary code, that contains leftovers from other projects. It has begun many years ago from scratch for a different project, then it was forked a few times and one of the fork turned into current Unit project. So, we have to fight with this mess for the next one or two years until it turned out to a good final shape.

Since we are at the very beginning, it's hard to say what parts of that dead code will be eventually reworked or removed.

**Comment by hongzhidao** [comment]
I have the same confusion as other developers.
1. Currently, all guys discuss unit in Github. Do you also use mail group like nginx-devel@...?
2. We are willing to use UNIT. What if the feature is useful, but is not on the recent roadmap, 
    such as TCP, HTTP proxy. Do you plan to support it earlier in the develop branch?
    These features seem to implemented in the later of 2018.
3. The most important, the issue such as following, is it welcome to created?
    The code is in $NXT_LIB_SRCS, but not used yet.

```
diff -r e887b019cfa4 src/nxt_conn_proxy.c
--- a/src/nxt_conn_proxy.c	Mon Jan 01 16:31:07 2018 +0300
+++ b/src/nxt_conn_proxy.c	Thu Jan 04 15:00:29 2018 -0500
@@ -420,7 +420,10 @@
         }

         source->read = rb->next;
-        nxt_buf_free(source->mem_pool, rb);  // We should always keep the rb->start memory.
+
+        if (rb != p->client_buffer && rb != p->peer_buffer) {
+            nxt_buf_free(source->mem_pool, rb);
+        }
     }
```

**Comment by VBart** [comment]
> Currently, all guys discuss unit in Github. Do you also use mail group like nginx-devel@...?

Yes, see: http://mailman.nginx.org/mailman/listinfo/unit

> We are willing to use UNIT. What if the feature is useful, but is not on the recent roadmap,
such as TCP, HTTP proxy. Do you plan to support it earlier in the develop branch?
These features seem to implemented in the later of 2018.

Support for proxy is planned. More or less realistic ETA is about the second half of 2018.

> The most important, the issue such as following, is it welcome to created? The code is in $NXT_LIB_SRCS, but not used yet.

I don't think that fixing dead code is a good idea. It will be eventually rewritten or deleted.
