### ISSUE TITLE
Initial json configuration

### ISSUE THREAD

**Issue by urba1n** [nginx/unit#83]
It would be useful to be able to specify a default json configuration when starting the unitd process, specially when using it in a container. Currently a sidekick can be used, but it has to deal with controller reachability and sometime a timeout occurs.

**Comment by VBart** [comment]
You can configure Unit and then copy the `state` directory. It contains everything that Unit needed in order to start with the same configuration.

Where Unit looks for this directory by default is set with the `--state=/path/to/state/dir` configure option. Then it can be overridden on unitd startup by the `--state /path/to/state/dir` option. You can check the default setting by running `unitd --help`.

**Comment by urba1n** [comment]
It is working perfectly fine, thanks.
