### ISSUE TITLE
Static File download problem

### ISSUE THREAD

**Issue by mortezaom** [nginx/unit#833]
Hello to all,
I have setup my server with nginx unit and for start I have only a static site served by unit, but the problem is it don't create a resumable data downloading system.
My site is not a download site but I worder why this happens and how I fix this.

**Comment by mattxtaz** [comment]
I think this is because Unit doesn't appear to have any support for the Range, Accept-Ranges, Content-Range headers and 206 Partial Content responses.

I noticed this too when I tried to watch an mp4 video file from a share and found that I couldn't fast-forward or rewind it and it had to download the whole file before it started to play the video.

I guess this is something that is likely to be developed in the future but it would be nice to know if it's on the roadmap or not.

**Comment by tippexs** [comment]
This is currently not supported but we will have a look on it. We war having some features like `Accept-Ranges` and `gzip` in the backlog but they are currently not planed for the next two releases.
