### ISSUE TITLE
wordpress err

### ISSUE THREAD

**Issue by dxxt** [nginx/unit#85]
what about index.php cannot open `ERR_TOO_MANY_REDIRECTS` (http://173.82.245.153)
but admin page well? (http://173.82.245.153/wp-login.php)

I config nginx_wp.conf 
```
server {

   location / {
        root   /var/www;
        index  index.html index.htm index.php;
    }


    location ~ \.php$ {
        proxy_pass http://unit_backend;
        proxy_set_header Host $host;
    }
}
```
start.json
```
{
    "listeners": {
        "*:8300": {
            "application": "blogs"
        }
    },

    "applications": {
        "blogs": {
            "type": "php",
            "user": "www-data",
            "group": "www-data",
            "root": "/var/www",
            "index": "index.php"
        }
    }
}
```

**Comment by nshadrin** [comment]
Wordpress has two different URL schemes, one for the production application, another one for the admin panel. To accommodate both of them in the same time, we will need to create two applications in Unit, and create two separate locations in NGINX. See nginx.conf part and corresponding Unit API output below. We used both NGINX and Unit on the same machine. Change IPs and ports accordingly, if you scale them out.

In NGINX config, we made one location for general traffic flow. It searches for files, and if file is not found, it sends traffic to Unit's first application through a named location @index_php. That application uses the "script" parameter instead of "index" parameter. It means, all requests for not-found pages will be executed through the same "index.php" script of Wordpress. This will work for requests to "/" URL.

Then, we created another location for wp-admin traffic. It does not need to handle unknown URLs through the same script.

Then, for all requests to PHP files, we created a regex location, with proxy_pass to the generic Unit application that handles files directly.

You can use multiple other location to further segregate traffic or have different security settings.

See the following links for more details on nginx.conf:
nginx.org/r/location
nginx.org/r/try_files

```upstream index_php_upstream {
    server 127.0.0.1:8090; # Unit backend for index.php with "script" parameter
}

upstream direct_php_upstream {
    server 127.0.0.1:8091; # Unit backend for generic php file handling
}

server {
    root   /var/www;

    location / {
        try_files $uri @index_php;
    }

    location @index_php {
        proxy_pass http://index_php_upstream;
        proxy_set_header Host $host;
    }

    location /wp-admin {
        index index.php;
    }

    location ~* \.php$ {
        proxy_pass http://direct_php_upstream;
        proxy_set_header Host $host;
    }

}```

```{
    "listeners": {
        "127.0.0.1:8090": {
            "application": "script_index_php"
        },
        "127.0.0.1:8091": {
            "application": "direct_php"
        }
    },

    "applications": {
        "script_index_php": {
            "type": "php",
            "user": "www-data",
            "group": "www-data",
            "root": "/var/www",
            "script": "index.php"
        },
        "direct_php": {
            "type": "php",
            "user": "www-data",
            "group": "www-data",
            "root": "/var/www",
            "index": "index.php"
        }

    }
}```

**Comment by dxxt** [comment]
Cool！
Thank you so much!
