### ISSUE TITLE
Cannot run sendmail(8) from unit anymore (1.29.1)

### ISSUE THREAD

**Issue by jn0** [nginx/unit#852]
Attempt to run the classic `/usr/lib/sendmail -t` now leads to
```
2023-03-10 11:07:49 1paXn3-0006tO-N9 Failed to create spool file /var/spool/exim4//input//1paXn3-0006tO-N9-D: Permission denied
```
error as the `sendmail(8)` have lost its setuid capability.

Any attempt to specify
```json
"isolation": {}
```
and alikes were pointless.

Probably related: #734  #820 

PS. It's a Python 3.7 WSGI application, if it matters.
Yes, the Python is old and no way to upgrade (now).
It's ran via `subprocess.run(['/usr/lib/sendmail', '-t', '-f', SENDER], ..., check=True)` - nothing special here.
The **exim4 4.92-8+deb10u7** is used as MTA.
Platform: Debian GNU/Linux 10 (buster).

**Comment by igorlidin** [comment]
Same here, Ubuntu 18.04, package versions:
```
ii  unit                                   1.29.1-1~bionic                                          amd64        NGINX Unit
ii  unit-python3.7                         1.29.1-1~bionic                                          amd64        Python 3.7 module for NGINX Unit
```

Calling setuid binary (like /usr/lib/sendmail) from Python application now leads to `permission denied` error. Looks like that setuid bit on the binary is now somehow ignored.

Downgrading Unit to 1.28 solves the problem.

While running setuid binaries from Unit applications is not a very good idea in general, classic Unix mail submission using `sendmail` interface should be an exception. At least, that should be configurable.

**Comment by ac000** [comment]
@jno Can you confirm you are having this issue _without_ any _isolation_ config enabled?

@igorlidin This isn't intentionally broken...

**Comment by igorlidin** [comment]
@ac000 Here, no 'isolation'-related keyword in config at all, just basic Python app config.

**Comment by ac000** [comment]
Hi @i4ki. This is going back a few years! but do you remember when you added this code

```c
#if (NXT_HAVE_PR_SET_NO_NEW_PRIVS)                                              
    if (nxt_slow_path(process->isolation.new_privs == 0                         
                      && prctl(PR_SET_NO_NEW_PRIVS, 1, 0, 0, 0) != 0))          
    {                                                                           
        nxt_alert(task, "failed to set no_new_privs %E", nxt_errno);            
        return NXT_ERROR;                                                       
    }                                                                           
#endif
```

in commit e2b53e16c60ba1e3bbbe59172c184e97f889326b, what the intention of the PR_SET_NO_NEW_PRIVS prctl(2) option was?

By default was it to be enabled in any configuration or only when using rootfs and/or some isolation config?

(Due to a typo this prctl(2) was never actually activated until commit 763396b8be07be41b1baf336952fd222cbeb8db7)

**Comment by jn0** [comment]
> Can you confirm you are having this issue _without_ any _isolation_ config enabled?

Yes, I do.

**Comment by ac000** [comment]
@jno Does setting the above config option fix things for you?

The `PR_SET_NO_NEW_PRIVS` prctl(2) option is enabled in all configs, but the above config option should override it regardless if you're using other isolation features or not.

**Comment by i4ki** [comment]
hi @ac000 
it was not a type as it was never documented.  It was intentionally disabled at the last minute due to a problem we discovered but I don't remember what it was.

The original intention of the `no_new_privs` was just to increase security, so if using isolation, the application would not be able to gain privileges by other means (`suid`, `sgid` files, etc)

**Comment by ac000** [comment]
This feature has been disabled by [default](https://github.com/nginx/unit/commit/c18dd1f65b9eba988bb621a4b540fb6c7bda36c8).
