### ISSUE TITLE
Release RPMs for Fedora

### ISSUE THREAD

**Issue by williamjmorenor** [nginx/unit#87]
Hello, in the oficial comentation about installing NGINX Unit there is reference to a yum repo to install in RHEL and CentOS 6 and 7, can be posible to provides rpms builds for Fedora? maybe in a corp repo?

https://copr.fedorainfracloud.org/

Building the rpms in corp have the advantage that shoulb tested in Mageia two.

**Comment by defanator** [comment]
Hi @williamjmorenor, we currently do not have Fedora boxes in our own build farm, but we've added support for building Fedora RPMs recently (see https://github.com/nginx/unit/commit/f2090bce21e4fb47d11f992a76ef5c4da74c3233).

You can build binary packages by running `make all` in the `pkg/rpm` directory of cloned repository.

We are open to add more platforms for regular releases, but it would be good to collect some stats/feedback first.

**Comment by lcts** [comment]
For Fedora >= 29, building the package with the provided Makefile fails, because

- those versions use python 3.7 instead of 3.6
- the ruby module is compiled using an rpath for the ruby libraries, which rpmbuild does not permit.

In `auto/modules/ruby`:

```
  NXT_RUBY_LIBPATH=`$NXT_RUBY -r rbconfig -e 'printf("%s",RbConfig::CONFIG["libdir"])'`
  NXT_RUBY_LIBS="-L$NXT_RUBY_LIBPATH -Wl,-rpath,${NXT_RUBY_LIBPATH} -l$NXT_RUBY_LIBNAME $NXT_RUBY_LIBSCONF"
```

This might also affect Fedora 26-28, I haven't tested. On Fedora 29+, the ruby libs are in the default path, so the -Wl,rpath isn't needed and can just be removed. Maybe making the rpath conditional by first checking if the `NXT_RUBY_LIBS` is already in the path would be a good way of handling this more generally.

I've created a [fork including the necessary changes](https://github.com/lcts/unit/tree/fedora-pkg) but only tested building it on Fedora 29. For those who just want to try out Unit on Fedora, there is also [COPR](https://copr.fedorainfracloud.org/coprs/lcts/unit/).

**Comment by VBart** [comment]
@lcts Thanks for noticing that. It seems rpath isn't needed on other systems too and can be safely removed.

**Comment by remicollet** [comment]
+1 to have Fedora RPMs

**Comment by williamjmorenor** [comment]
Current documentación says unit can be installed in fedora, so I think this ticket can be closed

**Comment by VBart** [comment]
You're right.
