### ISSUE TITLE
[Docker] Problem with reconfiguration on docker

### ISSUE THREAD

**Issue by MrSipping** [nginx/unit#873]
Hi, I installed the new version of docker (1.30) with php. I wanted to ask how I could change the configuration of unit in docker without having to do an internal vim because if I change the configuration on the host which is copied to docker and then do a curl inside docker, it tells me reconfiguration success but in reality it didn't change anything . Thank you

**Comment by tippexs** [comment]
If you copy the configuration in the container, you have to edit it in the container or mount it instead of copying.

What's the use case? Would you like to initially configure unit for your PHP app or is it more a development use case? Happy to share a couple of ideas with you once it is clear what you try to accomplish.

**Comment by lcrilly** [comment]
Feedback timeout
