### ISSUE TITLE
PHP as external type application

### ISSUE THREAD

**Issue by Pimentero** [nginx/unit#887]
I am trying to make container with queues and their metrics. The idea is to make single container that will run queues and output their metrics at the same time. Here is example config:

```
{
    "listeners": {
        "*:9999": {
            "pass": "applications/app"
        }
    },
    "applications": {
        "app": {
            "type": "php",
            "working_directory": "/app/",
            "root": "/app/",
            "script": "index.php"
        },
        "queue": {
            "type": "external",
            "working_directory": "/app/",
            "executable": "/usr/local/bin/php",
            "arguments": [
                "-f",
                "/app/queue.php"
            ]
        }
    }
}
```

`index.php` is for outputting metrics and `queue.php` is for running jobs (eg. laravel horizon).
But it seems that unit processes only `queue` application. When I try to connect to 9999 port, it just hangs forever.
Is php as external type even possible?

**Comment by ac000** [comment]
Type "external" simply means rather than the runtime being built into a DSO and loaded into Unit at runtime. The application is built as a separate executable that links against libunit.

For example a C application that links against libunit and is built as an executable is an 'external' application.

In the case of PHP. we build the PHP runtime into a DSO that gets loaded into Unit at runtime and is thus _not_ an external application type.

You could if you really wanted to, build your own PHP runtime, link against libunit and build it as an executable, then it would be an external application. But there really shouldn't be any need for that.

Why do you think you need it as an external application?

> But it seems that unit processes only queue application. When I try to connect to 9999 port, it just hangs forever.

Hmm, are you sure? You have only told unit how to access the "app" application...

**Comment by Pimentero** [comment]
> Type "external" simply means rather than the runtime being built into a DSO and loaded into Unit at runtime. The application is built as a separate executable that links against libunit.

As I thought.. Thank you for the reply :)

> Why do you think you need it as an external application?

I want to make a contrainer that can run queues and report its metrics. There was hope, that unit can handle both tasks and be the only one "app" in the container. Like, you know, 1 app - 1 container :) Sure, there are other possible ways to do the tasks, just wanted to try.

> Hmm, are you sure? You have only told unit how to access the "app" application...

`queues` can't receive http traffic, so there is no need for the route. Here is htop from container (to prove queues are running without routes):

![image](https://github.com/nginx/unit/assets/3263831/29f5c62b-21c2-44e8-80fa-6804d1a8c8bc)
