### ISSUE TITLE
Equivalent of $realpath_root to avoid reload unit after deployment using symlink 

### ISSUE THREAD

**Issue by kitro** [nginx/unit#888]
Hi All!

Using https://github.com/deployphp/deployer to deploy a PHP application because it uses a symlink to point the `current` release  and to avoid reloading the php-fpm after each deployment in Nginx configuration I use `realpath_root` like this: 

```
location ~ \.php$ {
  include fastcgi_params;
  fastcgi_pass unix:/var/run/php/php-fpm.sock;
 fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
}
```

https://deployer.org/docs/7.x/avoid-php-fpm-reloading#the-problem
 
Is there any relative to `realpath_root` in Ngnix unit to avoid restarting unit after each deployment?

The unit config used:

```
{
	"listeners": {
		"*:80": {
			"pass": "routes"
		},

		"*:443": {
			"pass": "routes",
			"tls": {
				"certificate": "certbot1"
			}
		}
	},

	"routes": [
		{
			"match": {
				"scheme": "http"
			},
			"action": {
				"return": 301,
				"location": "https://${host}${request_uri}"
			}
		},
		{
			"match": {
				"uri": "!/index.php"
			},

			"action": {
				"share": "/var/www/mysite/current/public$uri",
				"fallback": {
					"pass": "applications/mysite"
				}
			}
		}
	],

	"applications": {
		"mysite": {
			"type": "php",
			"root": "/var/www/mysite/current/public/",
			"script": "index.php"
		}
	}
}
```

Thank you for your help!

**Comment by lcrilly** [comment]
Hi kitro, thanks for the issue.

Are you saying that `SCRIPT_FILENAME` is being cached due to the symlink, and that restarting Unit is necessary to re-resolve it?

The first thing I'd like to explore is [restarting just the application](https://unit.nginx.org/configuration/#process-management) (not Unit). This should direct requests to the new deployment without interrupting requests.
```shell
unitc /control/applications/mysite/restart
-- OR --
curl -X GET --unix-socket /path/to/control.unit.sock http://localhost/control/applications/mysite/restart
```
Another approach might be to use the Deployer API to reconfigure Unit with the true directory name (instead of the symlink) `after()` the deployment. Deployer assumes a static HTTP server configuration whereas with Unit we can reconfigure dynamically as often as we want. But I guess this level of integration would also need do rollbacks, etc.

Finally, if we don't have a good solution or workaround then we can look at adding something like `resolve_root_symlink` directly to Unit's PHP module.

**Comment by kitro** [comment]
Hi Liam!

Yes, it looks the`SCRIPT_FILENAME` cached when the application started. 

The user that launched the deployment doesn't have permission to run `unitc`. But I will try to find a workaround to do it 👍 .

Thank you!

**Comment by lcrilly** [comment]
> But I will try to find a workaround to do it

Please let us know either way

**Comment by kitro** [comment]
Hi @lcrilly !

I get to add the deploy user to sudoers so can restart the application, IMHO it seems not like a good solution.

Letting unit resolve the real path of the symlink automatically is better than adding a user to sudoers that which may introduce some security risks.

Thank you!

**Comment by lcrilly** [comment]
Understood. That is not ideal. Marking as enhancement!

**Comment by ac000** [comment]
The problem is that at startup we run "root" through realpath(3) and store that. That stored path will persist and be used as the path to the script until the module is reloaded.

This breaks more than just the opcache, as even without the opcache, you need to restart the app to pick up the new version when using the current symlink technique.

For this to work we'd need to do this (call _nxt_php_set_target()_) on every request... there may be some trickery we can do to lessen the hit.

**Comment by kitro** [comment]
Hi All!

For now, in `visudo` I allowed the deployer user to restart the unit application, I limited their privilege to access only to `/usr/bin/curl -X GET --unix-socket /var/run/control.unit.sock*` I think is okay now.

Thank you!
